prefix ?= /usr/local
bindir = $(prefix)/bin
SYS := $(shell $(CC) -dumpmachine)

build:
	cargo build --release
install: build
ifneq (, $(findstring darwin, $(SYS)))
	test ! -d $(resourcedir) && mkdir -p $(resourcedir)

	install "target/release/rcheckbook" "$(bindir)/rcheckbook"
else
	install -D "target/release/rcheckbook" "$(bindir)/rcheckbook"
endif
uninstall:
	rm -rf "$(bindir)/rcheckbook"
clean:
	rm -rf target
.PHONY: build install uninstall clean